package com.ge.ev.notification.status;

/**
 * Created by 212391398 on 5/2/17.
 */
public enum NotificationServiceResponseStatus {
  GeneralError(NotificationStatusConstants.GENERAL_ERROR_VAL),
  Ok(NotificationStatusConstants.OK_1000_VAL),
  NotificationConfigurationDoesNotExist(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_DOES_NOT_EXIST_1001_VAL),
  NotificationTenantDoesNotExist(NotificationStatusConstants.NOTIFICATION_TENANT_DOES_NOT_EXIST_1002_VAL),
  NotificationSendError(NotificationStatusConstants.NOTIFICATION_SEND_ERROR_1003_VAL),
  NotificationTenantIdMismatch(NotificationStatusConstants.NOTIFICATION_TENANT_ID_MISMATCH_1004_VAL),
  NotificationTenantMissing(NotificationStatusConstants.NOTIFICATION_TENANT_MISSING_1005_VAL),
  NotificationSearchQueryMissing(NotificationStatusConstants.NOTIFICATION_SEARCH_QUERY_MISSING_1006_VAL),
  NotificationInvalidSearchQueryString(NotificationStatusConstants.NOTIFICATION_INVALID_SEARCH_QUERY_STRING_1007_VAL),
  NotificationConfigurationAddError(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_ADD_ERROR_1008_VAL),
  NotificationConfigurationPayloadLimit(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_PAYLOAD_LIMIT_STRING_1009_VAL),
  NotificationConfigurationTenantIdMismatch(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_TENANT_ID_MISMATCH_1010_VAL),
  NotificationConfigurationEmailValidation(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_EMAIL_VALIDATION_1011_VAL),
  NotificationEmailMessageValidation(NotificationStatusConstants.NOTIFICATION_EMAIL_MESSAGE_VALIDATION_1012_VAL),
  NotificationEmailMessageQueued(NotificationStatusConstants.NOTIFICATION_EMAIL_MESSAGE_QUEUED_1013_VAL),
  NotificationEmailDailyLimitReached(NotificationStatusConstants.NOTIFICATION_EMAIL_DAILY_LIMIT_REACHED_1014_VAL),
  NotificationEmailMonthylLimitReached(NotificationStatusConstants.NOTIFICATION_EMAIL_MONTHLY_LIMIT_REACHED_1015_VAL),
  NotificationGeneralError(NotificationStatusConstants.NOTIFICATION_GENERAL_ERROR_1016_VAL),
  NotificationAttachmentError(NotificationStatusConstants.NOTIFICATION_EMAIL_ATTACHMENT_ERROR_1017_VAL),
  NotificationWebhookSuccess(NotificationStatusConstants.NOTIFICATION_EMAIL_WEBHOOK_OK_1018_VAL),
  NotificationWebhookFail(NotificationStatusConstants.NOTIFICATION_EMAIL_WEBHOOK_FAIL_1019_VAL),
  NotificationConfigurationPerTenantLimit(NotificationStatusConstants.NOTIFICATION_CONFIGURATION_TENANT_LIMIT_1020_VAL),
  NotificationEmailsPerTenantLimit(NotificationStatusConstants.NOTIFICATION_EMAILS_PER_TENANT_LIMIT_1021_VAL),
  NotificationTemplateDoesNotExist(NotificationStatusConstants.NOTIFICATION_TEMPLATE_DOES_NOT_EXIST_1022_VAL),
  NotificationTemplateMatchersDoesNotExist(NotificationStatusConstants.NOTIFICATION_TEMPLATE_MATCHERS_DOES_NOT_EXIST_1023_VAL),
  NotificationTemplateMatchersInvalidEndDate(NotificationStatusConstants.NOTIFICATION_TEMPLATE_MATCHERS_INVALID_END_DATE_1024_VAL),
  NotificationTemplateMatchersRecipientDoesNotExist(NotificationStatusConstants.NOTIFICATION_TEMPLATE_MATCHERS_RECIPIENT_DOES_NOT_EXIST_1025_VAL),
  NotificationTemplateMatchersRecipientAlreadyExist(NotificationStatusConstants.NOTIFICATION_TEMPLATE_MATCHERS_RECIPIENT_ALREADY_EXIST_1026_VAL),
  NotificationTemplateMatchersRecipientInvalidEndDate(NotificationStatusConstants.NOTIFICATION_TEMPLATE_MATCHERS_RECIPIENT_INVALID_END_DATE_1027_VAL),
  NotificationTemplateSubscriptionNameRequired(NotificationStatusConstants.NOTIFICATION_TEMPLATE_SUBCRIPTION_NAME_REQUIRED_1028_VAL),
  NotificationTemplateSubscriptionDomainRequired(NotificationStatusConstants.NOTIFICATION_TEMPLATE_SUBCRIPTION_DOMAIN_REQUIRED_1029_VAL),
  NotificationTemplateSubscriptionInvalidEndDate(NotificationStatusConstants.NOTIFICATION_TEMPLATE_UBCRIPTION_INVALID_END_DATE_1030_VAL),
  NotificationTemplateSubscriptionNameAlreadyExists(NotificationStatusConstants.NOTIFICATION_TEMPLATE_SUBCRIPTION_NAME_ALREADY_EXISTS_1031_VAL),
  NotificationTemplateSubscriptionDoesNotExists(NotificationStatusConstants.NOTIFICATION_TEMPLATE_SUBCRIPTION_DOES_NOT_EXISTS_1032_VAL);

  private final Long value;

  NotificationServiceResponseStatus(final Long value)
  {
    this.value = value;
  }

  public Long getValue() { return value; }
}
